---
title: "Your blog post title"
date: YYYY-MM-DD
---

title: My title
author: GitHub User
theme: minima
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here is my site. I will be creating my new site here.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
